added ADC Module to Lizard
zauberzeug/lizard pull request #50
Opened 2024-06-28 14:04 UTC by JensOgorek

Created a module that can read Analogue signals with the ESP32's ADC modules.
Crate ADC with `adc = Adc()` and read data with `adc.read(adc_unit, channel, attenuation)`. The reading can be stopped with `adc.stop()`  and the interval delay can be changed with `adc.set_delay(value in ms)` .
The exact GPIO to adc_channel configurations, attenuation levels and other requirements can be found in the ESP documentation.

Stable State:
- ESP works under the usual conditions
- ESP continues to work under the usual conditions while reading a signal with the ADC module
- ESP continues to work under the usual conditions after reading a signal with the ADC module

Commit Messages:

- added read with voltage output
- added read_raw with bit output
- added set_delay
- added stop
- added docs
- added validation
- added module in callable modules
- changed misc

2024-07-01 14:34 UTC, falkoschindler requested changes
As discussed with @JensOgorek, we'd like to simplify API and implementation like this:
```py
adc = Adc(channel, number[, attenuation])

# or property?
adc.attenuation = 0
adc.attenuation = 2.5
adc.attenuation = 6
adc.attenuation = 11

# or set method?
adc.set_attenuation(11)

# step function writes data to properties:
adc.raw_value: integer
adc.voltage: number
```

2024-07-05 09:42 UTC, JensOgorek commented
Updated to work with properties. The ADC module is now called like ```adc = Adc(channel, number[, attenuation])``` and the values can be accessed with ```adc.raw_value``` and ```adc.voltage```

2024-07-05 12:31 UTC, JensOgorek commented
Changed the attenuation level input to match the attenuation db levels: 0, 2.5, 6 & 11

2024-07-10 14:16 UTC, falkoschindler approved these changes

2024-07-10 14:17 UTC, merged