Proxy defaults
zauberzeug/lizard pull request #97
Opened 2024-11-15 14:35 UTC by JensOgorek

Handle default properties for proxies on creation without expander esp being ready.

This is a followup for #18

The defaults are handled by a static function in the module class.

- [ ] create functionality to get defaults
- [ ] handle new creation of properties
- [ ] handle properties in proxy
- [ ] change input & output module
- [ ] test current version
- [ ] add all modules

2024-11-15 15:03 UTC, falkoschindler commented on main/modules/module.cpp
> +}
@JensOgorek Can't we avoid the need for countless if-conditions and use inheritance instead?

2024-11-15 15:12 UTC, JensOgorek commented
Replaced the static default_properties() methods with a virtual get_default_properties() function in the Module class, allowing each module type to define its own properties while eliminating the need for a separate list to maintain.

2024-11-15 15:15 UTC, falkoschindler commented on main/modules/output.cpp
> +    this->properties = this->get_default_properties();
@JensOgorek I think we can do that in the `Module` base class. Then individual modules only need to overwrite `get_default_properties` and are done.

2024-11-15 15:36 UTC, JensOgorek commented on main/modules/output.cpp
> +    this->properties = this->get_default_properties();
It seems like that creates a null pointer with boot loop.
Checked the core dump (with input and its subclasses):

The issue is that we're trying to access properties before they're initialized. The sequence is:
- Module constructor runs
- Tries to call virtual get_default_properties()
- But derived class (GpioInput) isn't fully constructed yet
- Crash when trying to access uninitialized properties

2024-11-19 09:36 UTC, falkoschindler requested changes
As we just discussed, we should keep the initial "level" and "change" values 0.

Apart from that, we can't call `Module.create` on the core ESP. We need a different solution.

2024-11-19 09:36 UTC, falkoschindler commented on main/modules/output.cpp
> +    this->properties = this->get_default_properties();
Strange...

2024-11-19 09:36 UTC, falkoschindler commented on main/modules/input.cpp
> +        {"active", std::make_shared<BooleanVariable>(false)}};
Why did you change the initial values here?

2024-11-19 09:36 UTC, falkoschindler commented on main/modules/output.cpp
> +        {"change", std::make_shared<IntegerVariable>(-1)}};
Same here. If we change the initial value to -1, I guess we should mention it in the documentation.
But I still feel like 0 is also a good initial value. The pin is kind of "off" when starting Lizard.
Starting with -1 might lead to a change of 2, which is rather arbitrary and unexpected.

2024-11-19 09:36 UTC, falkoschindler commented on main/modules/input.cpp
> +        {"change", std::make_shared<IntegerVariable>(-1)},
```suggestion
        {"level", std::make_shared<IntegerVariable>()},
        {"change", std::make_shared<IntegerVariable>()},
```

2024-11-19 09:36 UTC, falkoschindler commented on main/modules/output.cpp
> +        {"change", std::make_shared<IntegerVariable>(-1)},
```suggestion
        {"level", std::make_shared<IntegerVariable>()},
        {"change", std::make_shared<IntegerVariable>()},
```

2024-11-19 15:25 UTC, falkoschindler commented
@JensOgorek Whatever you did, somehow this PR now also contains changes from main which makes it hard to review. 😕

2024-11-19 16:04 UTC, JensOgorek commented
> @JensOgorek Whatever you did, somehow this PR now also contains changes from main which makes it hard to review. 😕

I got it fixed. Somehow, the main > proxy_defaults merge failed.

2024-11-19 16:57 UTC, falkoschindler requested changes
There are still changes from main contained in this PR, like the whole "check_strapping_pins" topic in expander.cpp.

Maybe we need to start over with a fresh branch, cherry-pick individual commits and delete and burn this branch afterwards... 🔥

2024-11-19 17:14 UTC, JensOgorek commented
> There are still changes from main contained in this PR, like the whole "check_strapping_pins" topic in expander.cpp.
> 
> Maybe we need to start over with a fresh branch, cherry-pick individual commits and delete and burn this branch afterwards... 🔥

Good idea, I bring the flamethrower tomorrow

2024-11-20 16:03 UTC, JensOgorek commented
Flamethrower was active, and we have a new pull request with #104

2024-11-20 16:03 UTC, closed without merging